package com.discord.api.guild;

public enum GuildFeature {
    VIP_REGIONS,
    INVITE_SPLASH,
    VANITY_URL,
    VERIFIED,
    MORE_EMOJI,
    BANNER,
    PARTNERED,
    COMMERCE,
    NEWS,
    DISCOVERABLE,
    FEATURABLE,
    ANIMATED_ICON,
    COMMUNITY,
    MEMBER_VERIFICATION_GATE_ENABLED,
    PREVIEW_ENABLED
}
