val androidTargetSdkVersion by extra(33)
val androidMinSdkVersion by extra(21)
val androidBuildToolsVersion by extra("33.0.0")
val androidCompileSdkVersion by extra(33)
val androidNdkVersion by extra("25.1.8937393")
val androidCmakeVersion by extra("3.22.1+")
