name: Blank Template
description: Use this template ONLY IF the other templates do not fit! DO NOT ASK FOR AN UNBAN FROM THE ALIUCORD DISCORD SERVER. DO NOT ASK FOR MISCELLANEOUS SUPPORT.
labels: []
body:
  - type: textarea
    id: info-sec
    attributes:
      label: Tell us all about it.
      description: Go nuts, let us know what you're wanting to bring attention to.
      placeholder: ...
    validations:
      required: true
  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: Did you check to make sure this issue you're bringing forward has not already been mentioned?
      options:
        - label: I did indeed check to make sure the issue is original!
          required: true
