name: Blank Template
description: Use this ONLY if your issue does not fit into another TEMPLATE. DO NOT ASK FOR AN UNBAN FROM THE ALIUCORD DISCORD. THIS REPO IS FOR DEVELOPMENT, NOT SUPPORT.
labels: []
body:
  - type: textarea
    id: info-sec
    attributes:
      label: Tell us all about it.
      description: Go nuts, let us know what you're wanting to bring attention to.
      placeholder: ...
    validations:
      required: true
  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: Did you check to make sure this issue you're bringing forward has not already been mentioned?
      options:
        - label: I did indeed check to make sure the issue is original!
          required: true
