name: Aliucord Bug Report
description: Create a bug report for Aliucord itself, to report bugs in plugins please go to our support server or the plugin's repository and make an issue there instead.
labels: [bug]
body:
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Who on Discord is making this request? Not required.
      placeholder: username#0000
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: What happens when the bug occurs?
      description: Where does this bug occur, when does it occur, etc.
      placeholder: The bug happens sometimes when I do ..., causing the app to crash. I think it happens because of ..., I hope that can help!
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the expected behaviour?
      description: Simply detail what the expected behaviour is.
      placeholder: I expect Aliucord to open the ... page instead of ..., it prevents me from doing ... and it is annoying.
    validations:
      required: true
  - type: textarea
    id: steps-to-take
    attributes:
      label: How do you recreate this bug?
      description: Give us a list of steps in order to recreate the bug.
      placeholder: |
        1. Do ...
        2. Then ...
        3. Do this ..., ... and then ...
        4. Observe "the bug"
    validations:
      required: true
  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: Did you check to make sure the bug you've found has not already been reported? Keep in mind that bugs can resurface, so if it's been reported before maybe it's come back!
      options:
        - label: I did indeed check to make sure the bug report is applicable!
          required: true