name: Bug/Crash Report
description: Create a bug or crash report for Aliucord itself. To report bugs or crashes related to plugins, please go to our support server, or the plugin's repository and make an issue there instead.
labels: [bug]
body:
  - type: input
    id: discord
    attributes:
      label: Discord Account
      description: Who on Discord is making this request? Not required.
      placeholder: username#0000
    validations:
      required: false
  - type: textarea
    id: bug-description
    attributes:
      label: What happens when the bug or crash occurs?
      description: Where does this bug or crash occur, when does it occur, etc.
      placeholder: The bug/crash happens sometimes when I do ..., causing this to not work/the app to crash. I think it happens because of ..., I hope that can help!
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the expected behaviour?
      description: Simply detail what the expected behaviour is.
      placeholder: I expect Aliucord to open the ... page instead of ..., it prevents me from doing ... and it is annoying.
    validations:
      required: true
  - type: textarea
    id: steps-to-take
    attributes:
      label: How do you recreate this bug or crash?
      description: Give us a list of steps in order to recreate the bug or crash.
      placeholder: |
        1. Do ...
        2. Then ...
        3. Do this ..., ... and then ...
        4. Observe "the bug" or "the crash"
    validations:
      required: true
  - type: textarea
    id: crash-log
    attributes:
      label: Crash-log
      description: Paste the crash-log for your plugin between the two sections of "```".
      value: |
        ```
        Replace this text with your crash-log.
        ```
      validations:
        required: true
  - type: checkboxes
    id: agreement-check
    attributes:
      label: Request Agreement
      description: Did you check to make sure the bug or crash you've found has not already been reported? Keep in mind that bugs and crashes can resurface, so if it's been reported before maybe it's come back!
      options:
        - label: I did indeed check to make sure the bug or crash report is applicable!
          required: true