@file:Suppress("NOTHING_TO_INLINE", "UNCHECKED_CAST")

package com.aliucord.patcher

import de.robv.android.xposed.XC_MethodHook.MethodHookParam

inline operator fun MethodHookParam.component1() = this

inline operator fun <T> MethodHookParam.component2(): T = args[0] as T
inline operator fun <T> MethodHookParam.component3(): T = args[1] as T
inline operator fun <T> MethodHookParam.component4(): T = args[2] as T
inline operator fun <T> MethodHookParam.component5(): T = args[3] as T
inline operator fun <T> MethodHookParam.component6(): T = args[4] as T
inline operator fun <T> MethodHookParam.component7(): T = args[5] as T
inline operator fun <T> MethodHookParam.component8(): T = args[6] as T
inline operator fun <T> MethodHookParam.component9(): T = args[7] as T
inline operator fun <T> MethodHookParam.component10(): T = args[8] as T
inline operator fun <T> MethodHookParam.component11(): T = args[9] as T
inline operator fun <T> MethodHookParam.component12(): T = args[10] as T
inline operator fun <T> MethodHookParam.component13(): T = args[11] as T
inline operator fun <T> MethodHookParam.component14(): T = args[12] as T
inline operator fun <T> MethodHookParam.component15(): T = args[13] as T
inline operator fun <T> MethodHookParam.component16(): T = args[14] as T
inline operator fun <T> MethodHookParam.component17(): T = args[15] as T
inline operator fun <T> MethodHookParam.component18(): T = args[16] as T
inline operator fun <T> MethodHookParam.component19(): T = args[17] as T
inline operator fun <T> MethodHookParam.component20(): T = args[18] as T
inline operator fun <T> MethodHookParam.component21(): T = args[19] as T
inline operator fun <T> MethodHookParam.component22(): T = args[20] as T
inline operator fun <T> MethodHookParam.component23(): T = args[21] as T
inline operator fun <T> MethodHookParam.component24(): T = args[22] as T
inline operator fun <T> MethodHookParam.component25(): T = args[23] as T
inline operator fun <T> MethodHookParam.component26(): T = args[24] as T
inline operator fun <T> MethodHookParam.component27(): T = args[25] as T
inline operator fun <T> MethodHookParam.component28(): T = args[26] as T
inline operator fun <T> MethodHookParam.component29(): T = args[27] as T
inline operator fun <T> MethodHookParam.component30(): T = args[28] as T
inline operator fun <T> MethodHookParam.component31(): T = args[29] as T
inline operator fun <T> MethodHookParam.component32(): T = args[30] as T
inline operator fun <T> MethodHookParam.component33(): T = args[31] as T
inline operator fun <T> MethodHookParam.component34(): T = args[32] as T
inline operator fun <T> MethodHookParam.component35(): T = args[33] as T
inline operator fun <T> MethodHookParam.component36(): T = args[34] as T
inline operator fun <T> MethodHookParam.component37(): T = args[35] as T
inline operator fun <T> MethodHookParam.component38(): T = args[36] as T
inline operator fun <T> MethodHookParam.component39(): T = args[37] as T
inline operator fun <T> MethodHookParam.component40(): T = args[38] as T
inline operator fun <T> MethodHookParam.component41(): T = args[39] as T
inline operator fun <T> MethodHookParam.component42(): T = args[40] as T
inline operator fun <T> MethodHookParam.component43(): T = args[41] as T
inline operator fun <T> MethodHookParam.component44(): T = args[42] as T
inline operator fun <T> MethodHookParam.component45(): T = args[43] as T
inline operator fun <T> MethodHookParam.component46(): T = args[44] as T
inline operator fun <T> MethodHookParam.component47(): T = args[45] as T
inline operator fun <T> MethodHookParam.component48(): T = args[46] as T
inline operator fun <T> MethodHookParam.component49(): T = args[47] as T
inline operator fun <T> MethodHookParam.component50(): T = args[48] as T
inline operator fun <T> MethodHookParam.component51(): T = args[49] as T
inline operator fun <T> MethodHookParam.component52(): T = args[50] as T
inline operator fun <T> MethodHookParam.component53(): T = args[51] as T
inline operator fun <T> MethodHookParam.component54(): T = args[52] as T
inline operator fun <T> MethodHookParam.component55(): T = args[53] as T
inline operator fun <T> MethodHookParam.component56(): T = args[54] as T
inline operator fun <T> MethodHookParam.component57(): T = args[55] as T
inline operator fun <T> MethodHookParam.component58(): T = args[56] as T
inline operator fun <T> MethodHookParam.component59(): T = args[57] as T
inline operator fun <T> MethodHookParam.component60(): T = args[58] as T
inline operator fun <T> MethodHookParam.component61(): T = args[59] as T
inline operator fun <T> MethodHookParam.component62(): T = args[60] as T
inline operator fun <T> MethodHookParam.component63(): T = args[61] as T
inline operator fun <T> MethodHookParam.component64(): T = args[62] as T
inline operator fun <T> MethodHookParam.component65(): T = args[63] as T
inline operator fun <T> MethodHookParam.component66(): T = args[64] as T
inline operator fun <T> MethodHookParam.component67(): T = args[65] as T
inline operator fun <T> MethodHookParam.component68(): T = args[66] as T
inline operator fun <T> MethodHookParam.component69(): T = args[67] as T
inline operator fun <T> MethodHookParam.component70(): T = args[68] as T
inline operator fun <T> MethodHookParam.component71(): T = args[69] as T
inline operator fun <T> MethodHookParam.component72(): T = args[70] as T
inline operator fun <T> MethodHookParam.component73(): T = args[71] as T
inline operator fun <T> MethodHookParam.component74(): T = args[72] as T
inline operator fun <T> MethodHookParam.component75(): T = args[73] as T
inline operator fun <T> MethodHookParam.component76(): T = args[74] as T
inline operator fun <T> MethodHookParam.component77(): T = args[75] as T
inline operator fun <T> MethodHookParam.component78(): T = args[76] as T
inline operator fun <T> MethodHookParam.component79(): T = args[77] as T
