name: Build Injector

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-injector.yml
      - Injector/**

jobs:
  build-injector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: src

      - name: Checkout builds
        uses: actions/checkout@master
        with:
          ref: builds
          path: builds

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@3404b45d4c43e74e30dcad1a47fb89a0573f5a7e # v2.0.6

      - name: Build Injector
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew :Injector:make
          cp Injector/build/Injector.dex $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          git commit -m "Build $GITHUB_SHA"
          git push
